### ISSUE TITLE
Speedup the Integrated Development Environment (IDE)

### ISSUE THREAD

**Issue by adamrepos** [input-output-hk/haskell-course#23]
From: https://github.com/input-output-hk/haskell-course/issues/6

I understand that IDE is coming but the timeline is a discouraging. Developers are struggling. They can’t wait months. See: https://forum.cardano.org/t/developers-are-having-dismal-experience-building-on-cardano/110080 

There are projects (like Sundaeswap, JPG.store, etc) currently running on Cardano. I can imagine they already developed in-house IDE or something similar. Can you reach out and ask them to open-source their tools? Or maybe form some kind of co-development of a Cardano IDE, based on what they already have, to be share with the ecosystem? That would speed things up immensely. Developers, especially new ones wanting to get into Cardano, desperately need the IDE. Most of them can't wait months. 

This is urgent. Make it happens before they go build elsewhere.

**Comment by rober-m** [comment]
Hi @adamrepos! I hear you! I spend most of my time teaching and helping people that struggle with setting up the dev environment. 

The thing is, this (#6) is a problem that (in general) only beginners have. Once you understand how everything works (like the engineers of Sundaswap and other companies), you usually don't need anything more than what is already out there. So they don't need to build in-house IDEs.

This doesn't mean this is not an important issue. **It's huge!** That's why we're doing a bunch of things to help beginners adopt the technologies. We're making this and the PPP course, writing tutorials and documentation, creating tools like [CHaP](https://input-output-hk.github.io/cardano-haskell-packages/) to make it easier to use Plutus and other IOG libraries, etc. And we're also doing what you just asked us to do. We're identifying companies in the ecosystem (like Plank and TxPipe) that are generating open-source tools and resources and partnering up, contracting, or helping them in some way to speed up the process.

**The closest thing we have to Remix right now is [Demeter](https://demeter.run/) from TxPipe.** You can use it for free, and we'll use it in our next PPP to avoid everyone getting stuck setting up the environment. I really hope that's enough for now. But we'll keep working to make everything easier to learn and use! 💪

**Comment by adamrepos** [comment]
"you usually don't need anything more than what is already out there. So they don't need to build in-house IDEs"

For one, when you wanna test the contract with the testnet, there is no tool to automate the process. You have to manually create transaction and submit it using cardano-cli. Copy and paste each utxo by hands. That's very inefficient way to test things.

I am sure existing dapps has this process automated.

So yes, the tools are there. But the whole process is far from optimal. IDE is optimal. And we need it. Ethereum, Solana, Algorand has it figured out. We are lacking behind.

**Comment by adamrepos** [comment]
@rober-m 

Algorand official tutorial:
https://youtu.be/a25ol9NPBTM

You might find something in there useful when making tutorials.
