### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vamanfredi** [input-output-hk/haskell-course#7]
Hi Rober, I thought it was a great idea to have a community translation so I´ve forked and translated the repo to Spanish (up to lesson 1).
Here´s the [repo](https://github.com/vamanfredi/haskell-course-ES), anyone can help improving it.
Saludos ;)

**Comment by rober-m** [comment]
That's awesome! Thank you, @vamanfredi, for your effort! Last week we had a team meeting, and based on the push and willingness of the community to help, we decided to devote resources to work with the community and translate the course to Spanish. 

We don't have the details yet. But for now, it's just for Spanish (because I can check the translations myself). We'll provide more information soon, but we'll likely create a separate repo and curate and edit the content the community gives us. I may also record the lessons in Spanish, but that would be after the English version is done and if the community asks for it.

Thank you again @vamanfredi!

**Comment by rober-m** [comment]
Hi @vamanfredi!

I have great news! 😃 I adapted the repository to accommodate the Spanish translation! Would you be kind enough to do a PR with your translations? I want to keep on record that you contributed to these.

Check out the [ES-translation](https://github.com/input-output-hk/haskell-course/tree/main/ES-translation) folder. There, I added dummy files as placeholders indicating what we'll translate (since we don't need to duplicate configurations and such).

The solutions will be in a separate branch called [solutions-es](https://github.com/input-output-hk/haskell-course/tree/solutions-es).
